// A small en+mr label map — the console is bilingual but does not need the
// app's full i18n machinery. English leads (recyclers read it); Marathi
// supports.
export const LABELS = {
  en: {
    rates: "Rates",
    acceptances: "Incoming",
    verify: "Verify & sign",
    history: "History",
    flags: "Flags",
    login: "Sign in",
    logout: "Sign out",
    publish: "Publish",
    acknowledge: "Acknowledge",
    decline: "Decline",
    inaction_note: "Doing nothing means the collector arrives as planned.",
    final_price: "Final price after inspection",
    inspected_condition: "Condition after inspection",
    downgrade_reason: "Reason for a lower grade",
    submit_handover: "Send to collector",
    awaiting_collector: "Waiting for the collector to confirm",
    estimated: "Estimated",
    published: "Published",
    paid: "Paid",
    within_budget: "Alert rate within target",
    over_budget: "Alert rate above target",
    admin_queue: "Queue",
    admin_recyclers: "Recyclers",
    admin_footer_note: "Flags rank transactions for human review. They are not findings of wrongdoing.",
    admin_no_flags: "No open flags — queue is empty",
    admin_insufficient_history: "Not enough history",
    admin_outcome_prompt: "Record an outcome",
    admin_outcome_justified: "Justified",
    admin_outcome_suspicious: "Suspicious",
    admin_outcome_disputed: "Disputed",
    admin_outcome_unresolved: "Unresolved",
    admin_outcome_invalid: "Invalid",
    admin_run_detection: "Run detection on unscored handovers",
    admin_published: "Published",
    admin_median_paid: "Actually paid (median, last 20)",
    admin_price_cut: "Price cut at handover",
    admin_downgrade_rate: "Downgrade exception rate",
    admin_reports: "Reports",
    admin_no_reports: "No reports — nothing collectors have flagged",
    admin_report_mark_reviewed: "Mark reviewed",
    admin_report_reviewed: "Reviewed",
    admin_report_status_open: "Open",
    admin_report_status_reviewed: "Reviewed",
    admin_report_status_all: "All",
    mpcb_verified_badge: "✓ MPCB Verified",
    admin_badges: "Badges",
    admin_badges_intro: "MPCB-listed recyclers. Revoking hides the green badge on their login — it does not touch MPCB authorisation status, which only the next MPCB refresh can change.",
    admin_badge_revoke: "Revoke",
    admin_badge_restore: "Restore",
    admin_badge_revoked_label: "Revoked",
    admin_badge_active_label: "Active",
    admin_no_verified_recyclers: "No MPCB-verified recyclers",
  },
  mr: {
    rates: "भाव",
    acceptances: "आलेले",
    verify: "तपासा",
    history: "इतिहास",
    flags: "इशारे",
    login: "प्रवेश",
    logout: "बाहेर",
    publish: "प्रकाशित करा",
    acknowledge: "स्वीकारले",
    decline: "नाकारले",
    inaction_note: "काही न केल्यास संग्राहक ठरल्याप्रमाणे येईल.",
    final_price: "तपासणीनंतरची किंमत",
    inspected_condition: "तपासणीनंतरची स्थिती",
    downgrade_reason: "कमी दर्जाचे कारण",
    submit_handover: "संग्राहकाला पाठवा",
    awaiting_collector: "संग्राहकाच्या पुष्टीची वाट",
    estimated: "अंदाजे",
    published: "जाहीर",
    paid: "दिले",
    within_budget: "इशारे मर्यादेत",
    over_budget: "इशारे मर्यादेबाहेर",
    admin_queue: "यादी",
    admin_recyclers: "रिसायकलर्स",
    admin_footer_note: "इशारे पुनरावलोकनासाठी क्रमवारी लावतात. हे गैरवर्तनाचे निष्कर्ष नाहीत.",
    admin_no_flags: "उघडे इशारे नाहीत",
    admin_insufficient_history: "पुरेसा इतिहास नाही",
    admin_outcome_prompt: "निकाल नोंदवा",
    admin_outcome_justified: "योग्य",
    admin_outcome_suspicious: "संशयास्पद",
    admin_outcome_disputed: "वादग्रस्त",
    admin_outcome_unresolved: "अनिर्णित",
    admin_outcome_invalid: "अवैध",
    admin_run_detection: "न तपासलेल्या व्यवहारांवर तपासणी चालवा",
    admin_published: "जाहीर केलेला दर",
    admin_median_paid: "प्रत्यक्ष दिलेले (मध्यक, शेवटचे २०)",
    admin_price_cut: "हस्तांतरणावेळी कापलेली किंमत",
    admin_downgrade_rate: "दर्जा-कपात दर",
    admin_reports: "तक्रारी",
    admin_no_reports: "कोणतीही तक्रार नाही",
    admin_report_mark_reviewed: "पुनरावलोकन झाले असे नोंदवा",
    admin_report_reviewed: "पुनरावलोकन झाले",
    admin_report_status_open: "उघड्या",
    admin_report_status_reviewed: "पुनरावलोकन झालेल्या",
    admin_report_status_all: "सर्व",
    mpcb_verified_badge: "✓ MPCB सत्यापित",
    admin_badges: "बॅज",
    admin_badges_intro: "MPCB-सूचीबद्ध रिसायकलर्स. रद्द केल्याने लॉगिनवरील हिरवा बॅज लपतो — MPCB अधिकृतता स्थितीवर परिणाम होत नाही, ती फक्त पुढील MPCB रिफ्रेशनेच बदलू शकते.",
    admin_badge_revoke: "रद्द करा",
    admin_badge_restore: "पुनर्संचयित करा",
    admin_badge_revoked_label: "रद्द केलेले",
    admin_badge_active_label: "सक्रिय",
    admin_no_verified_recyclers: "कोणतेही MPCB-सत्यापित रिसायकलर्स नाहीत",
  },
};

export function t(key, lang = "en") {
  return LABELS[lang]?.[key] ?? LABELS.en[key] ?? key;
}
